[book]
authors = ["Microsoft"]
language = "en"
multilingual = false
src = "src"
title = "TypeChat"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
curly-quotes = true
git-repository-url = "https://github.com/microsoft/TypeChat"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/microsoft/TypeChat/edit/main/site/{path}"